spring.application.name=SpringBootSecurityPostgresqlApplication

spring.datasource.url=jdbc:postgresql://pg-jesus-jrwar2000-24b9.c.aivencloud.com:12880/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

bezkoder.app.jwtSecret=iloveadsoftsitoiloveadsoftsitoiloveadsoftsito
bezkoder.app.jwtExpirationMs=86400000